// SPDX-License-Identifier: UNLICENSED

/**
  ZcToken is a mock which records arguments passed to its methods as well as
  provides setters allowing us to dictate method return values
*/

pragma solidity 0.8.16;

// present so that we can force a call from the mock to the consumer for testing of authRedeem
interface IRedeemer {
  function authRedeem(uint8, address, uint256, address, address, uint256) external returns (uint256);
}

contract ZcToken {
  // a struct to hold the arguments passed to transferFrom
  struct TransferFromArgs {
    address to;
    uint256 amount;
  }

  // mapping of arguments sent to burn. key is the passed in address.
  mapping (address => uint256) public burnCalled;
  // mapping of arguments sent to mint. key is the passed in address.
  mapping (address => uint256) public mintCalled;
  // mapping of arguments sent to transferFrom. key is passed from address.
  mapping (address => TransferFromArgs) public transferFromCalled;

  uint8 public protocol;
  address private underlyingReturn;
  uint256 private maturityReturn;
  address public cToken;
  address public redeemer;
  string public name;
  string public symbol;
  uint8 public decimals;
  // a boolean flag which allows us to dictate the return of burn().
  bool private burnReturn;
  // a boolean flag which allows us to dictate the return of mint().
  bool private mintReturn;
  // a boolean flag which allows us to dictate the return of transferFrom().
  bool private transferFromReturn;

  /// @param p Protocol Enum value
  /// @param u Underlying
  /// @param m Maturity
  /// @param c Compounding token
  /// @param r Redeeming contract address
  /// @param n Name
  /// @param s Symbol
  /// @param d Decimals
  constructor(uint8 p, address u, uint256 m, address c, address r, string memory n, string memory s, uint8 d) {
    protocol = p;
    underlyingReturn = u;
    maturityReturn = m;
    cToken = c;
    redeemer = r;
    name = n;
    symbol = s;
    decimals = d;
  }

  function burnReturns(bool b) public {
    burnReturn = b;
  }

  function burn(address f, uint256 a) public returns(bool) {
    burnCalled[f] = a;
    return burnReturn;
  }

  function mintReturns(bool b) public {
    mintReturn = b;
  }

  function mint(address f, uint256 a) public returns(bool) {
    mintCalled[f] = a;
    return mintReturn;
  }

  function underlyingReturns(address u) public {
    underlyingReturn = u;
  }
  
  // override what would be the autogenerated getter...
  function underlying() public view returns (address) {
    return underlyingReturn;
  }

  function maturityReturns(uint256 n) public {
    maturityReturn = n;
  }
  
  // override what would be the autogenerated getter...
  function maturity() public view returns (uint256) {
    return maturityReturn;
  }

  function transferFrom(address f, address t, uint256 a) public returns (bool) {
    TransferFromArgs memory args;
    args.to = t;
    args.amount = a;
    transferFromCalled[f] = args;
    return transferFromReturn;
  }

  function transferFromReturns(bool b) public {
    transferFromReturn = b;
  }

  // force a call from the mock to the redeemer's auth redeem function
  function authRedeem(uint8 p, address u, uint256 m, address f, address t, uint256 a) external {
    IRedeemer(redeemer).authRedeem(p, u, m, f, t, a);
  }
}
