// SPDX-License-Identifier: UNLICENSED

/**
  VaultTracker is a mock which records arguments passed to its methods as well as
  provides setters allowing us to dictate method return values
*/

pragma solidity 0.8.0;

contract VaultTracker {
  // can just be default as its not needed to be exposed...
  address public cTokenAddr;
  
  uint256 private maturityReturn;   

  /// @param m Maturity
  /// @param c C Token Address
  constructor(uint256 m, address c) {
    // we can set the privates in the constructor as well...
    maturityReturn = m;
    cTokenAddr = c;
  }

  function maturityReturns(uint256 n) public {
    maturityReturn = n;
  }
  
  // override what would be the autogenerated getter...
  function maturity() public view returns (uint256) {
    return maturityReturn;
  }
}
